### ISSUE TITLE
steveliles/debian-7.4.0-xfce source?

### ISSUE THREAD

**Issue by chuyskywalker** [steveliles/vagrant-boxes#1]
Hi Steve!

Came across the `steveliles/debian-7.4.0-xfce` base on Atlas and was wondering how you put that together? Do you have a packer.json file or something for it or did you build it from something else?

Thanks!

**Comment by steveliles** [comment]
Hi Jeff!

Pretty sure I just fired up VirtualBox and installed from an ISO, then packaged using `vagrant package --base` - it was my first ever vagrant box, and I was just following along the [guide](https://docs.vagrantup.com/v2/virtualbox/boxes.html).

best,
S.

**Comment by chuyskywalker** [comment]
Dang! I'd hoped it was programmatic. Thanks anyhow!
